### ISSUE TITLE
[BUG] MMB on copied buildings doesn't work

### ISSUE THREAD

**Issue by Netoen** [mircearoata/SatisfactoryAdvancedLogistics#10]
When you copied buildsing, say, with "Fill" the middle mouse button pipette doesn't work on such buildings.

**Comment by mircearoata** [comment]
Wrong mod, and there already is an open issue about this on Area Actions, you don't need to create a new one, it makes it harder for me to keep track of them

**Comment by Netoen** [comment]
Sorry about this.
