### ISSUE TITLE
Doesn't connect to existing belt

### ISSUE THREAD

**Issue by uecasm** [mircearoata/SatisfactoryAdvancedLogistics#11]
If you construct a belt, and then construct an Adjustable Splitter in the middle of the existing belt, the game splits the original belt into two new belts that appear to be connected, but don't actually transfer items through the splitter.

Workaround: delete the original belts after placing the splitter and then re-create them, then everything starts flowing as expected.

Maybe there's some extra "reattach" callback missing or something?  Might be something missing in SML itself though, or the game does something magic with standard splitters that isn't being exported.

**Comment by uecasm** [comment]
Possibly of note is that if you hover over the belts with the colour gun selected (so that it highlights their borders), when it's in the "bad" state the belts are split directly in two but still touch in the middle of the splitter, but after rebuilding them so they work, they stop at the edge of the splitter and there's a gap in the middle.  (And if you deconstruct a standard splitter when in this state, you actually see the belt was split into three pieces.)

**Comment by mircearoata** [comment]
It does the snapping to the belt automatically, and it connects the input and not the output, the vanilla splitters probably do some magic or the outputs are named somehow specific, I haven't figured it out yet

**Comment by mircearoata** [comment]
Fixed in v0.3.0
