### ISSUE TITLE
[MP] Ratios not working

### ISSUE THREAD

**Issue by ReallyNotBad** [mircearoata/SatisfactoryAdvancedLogistics#12]
![image](https://user-images.githubusercontent.com/52174629/77340360-77dab800-6d2d-11ea-9db0-22926ca3b4a5.png)

In Multiplayer the ratio is not working at all. 
Maybe I have overseen a setting or so.

Can you help me with that?

Thank you!

**Comment by mircearoata** [comment]
I think I know what happens, the values aren't sent to the host (99% sure, but can you check please). Multiplayer is infinitely more complicated than Singleplayer to program for...

**Comment by ReallyNotBad** [comment]
Yes, I tested it right now. 
When host changes settings all clients get updated
When client changes settings nothing happen to other clients, no matter how far or near to host player!

So we have a workaround for that issue. Same as for trains right now.

**Comment by mircearoata** [comment]
Fixed in v0.3.0
