### ISSUE TITLE
Infinite loop in Splitter

### ISSUE THREAD

**Issue by Dee-Fuse** [mircearoata/SatisfactoryAdvancedLogistics#13]
When (accidentally) setting "if full" to the same output as the configured output it will lock the game if this belt fills up.
Maybe remove the option for the same direction to prevent it from beeing selected.

![grafik](https://user-images.githubusercontent.com/7376678/77547410-72a47700-6ead-11ea-8417-9c2711fd00c8.png)

**Comment by koza1258** [comment]
I have the same problem.,

**Comment by jalil49** [comment]
Just posted a pull request with a fix deleting the option and also took the extra step of stopping you from send left to right and right to left creating another loop
