### ISSUE TITLE
new Release including lastest fixes

### ISSUE THREAD

**Issue by kesslerdev** [mircearoata/SatisfactoryAdvancedLogistics#15]
Hello, 
I would love to use your mod in my multiplayer factory, and specially mergers.
It seems last commits includes some fixes for mergers crashs.

Can you publish a new release including all fixes ? 

Thank you for fill the lack of overflow in this game !

**Comment by mircearoata** [comment]
It also includes a fix for the buildings not being placeable on belts, which breaks current saves, so I'm currently writing a fix for that, almost ready

**Comment by kesslerdev** [comment]
ok great, good luck for this bug !
