### ISSUE TITLE
Update 7 incompatible

### ISSUE THREAD

**Issue by tonich-sh** [mircearoata/SatisfactoryAdvancedLogistics#26]
Doesn't output anything

**Comment by mircearoata** [comment]
Thank you! Fixed in v0.3.7

**Comment by Tauschung** [comment]
Appreciate the update, but now my file won't even load with the mod active. It loaded fine before the mod update (albeit the splitters didn't work) and it loads with the mod turned off.

**Comment by mircearoata** [comment]
See #27 . Fixed in v0.3.8.
