### ISSUE TITLE
Game Crashing when placing Advanced splitter 

### ISSUE THREAD

**Issue by TheIntingFredi** [mircearoata/SatisfactoryAdvancedLogistics#27]
after i installed the mod i started placing 1 splitter and a few minutes later i tried placing a second one but the game crashed, no problem i thought and clicked on "send and restart" and after that on  "continue" back in game i tried again and it chrashed again so this time i completely restarted the game and after that i could place splitter on the ground but when i went back to building and tried my original place meant but there it crashed again 

Crash Diagnostic log:
Version: 209200, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: Steam, NetMode: Listen Server, IsUsingMods: Yes

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION 0x00000221abfea780

FactoryGame_SML_Win64_Shipping!FindOwnerPluginForMountPoint() [C:\ar-sml\_work\SatisfactoryModLoader\SatisfactoryModLoader\SML\Plugins\SML\Source\SML\Private\Util\BlueprintAssetHelperLibrary.cpp:81]
FactoryGame_SML_Win64_Shipping!UBlueprintAssetHelperLibrary::FindPluginNameByObjectPath() [C:\ar-sml\_work\SatisfactoryModLoader\SatisfactoryModLoader\SML\Plugins\SML\Source\SML\Private\Util\BlueprintAssetHelperLibrary.cpp:147]
FactoryGame_SML_Win64_Shipping!UBlueprintLoggingLibrary::LogImpl() [C:\ar-sml\_work\SatisfactoryModLoader\SatisfactoryModLoader\SML\Plugins\SML\Source\SML\Private\Util\BlueprintLoggingLibrary.cpp:26]
FactoryGame_SML_Win64_Shipping!UBlueprintLoggingLibrary::execLogWarning() [C:\ar-sml\_work\SatisfactoryModLoader\SatisfactoryModLoader\SML\Plugins\SML\Source\SML\Public\Util\BlueprintLoggingLibrary.h:59]
FactoryGame_CoreUObject_Win64_Shipping!ProcessLocalScriptFunction() [D:\TC_agent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1067]
FactoryGame_CoreUObject_Win64_Shipping!ProcessScriptFunction<void (__cdecl*)(UObject *,FFrame &,void *)>() [D:\TC_agent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:898]
FactoryGame_CoreUObject_Win64_Shipping!UObject::execLocalFinalFunction() [D:\TC_agent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:2997]
FactoryGame_CoreUObject_Win64_Shipping!ProcessLocalScriptFunction() [D:\TC_agent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1067]
FactoryGame_CoreUObject_Win64_Shipping!UObject::ProcessInternal() [D:\TC_agent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1156]
FactoryGame_CoreUObject_Win64_Shipping!UFunction::Invoke() [D:\TC_agent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:5589]
FactoryGame_CoreUObject_Win64_Shipping!UObject::ProcessEvent() [D:\TC_agent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1992]
FactoryGame_Engine_Win64_Shipping!AActor::ProcessEvent() [D:\TC_agent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Engine\Private\Actor.cpp:917]
FactoryGame_FactoryGame_Win64_Shipping!AFGBuildable::Factory_ReceiveTick() [D:\TC_agent\work\78a794e88763017d\UE4\Games\FactoryGame\Intermediate\Build\Win64\FactoryGame\Inc\FactoryGame\FGBuildable.gen.cpp:841]
FactoryGame_FactoryGame_Win64_Shipping!<lambda_894261a5d2fbb741922e1f3769159f93>::operator()() [D:\TC_agent\work\78a794e88763017d\UE4\Games\FactoryGame\Source\FactoryGame\Private\FGBuildableSubsystem.cpp:590]
FactoryGame_FactoryGame_Win64_Shipping!ParallelForImpl::TParallelForData<TFunctionRef<void __cdecl(int)> >::Process() [D:\TC_agent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Core\Public\Async\ParallelFor.h:177]
FactoryGame_FactoryGame_Win64_Shipping!TGraphTask<ParallelForImpl::TParallelForTask<TFunctionRef<void __cdecl(int)> > >::ExecuteTask() [D:\TC_agent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Core\Public\Async\TaskGraphInterfaces.h:886]
FactoryGame_Core_Win64_Shipping!FTaskThreadAnyThread::ProcessTasksUntilQuit() [D:\TC_agent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:887]
FactoryGame_Core_Win64_Shipping!FTaskThreadBase::Run() [D:\TC_agent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:541]
FactoryGame_Core_Win64_Shipping!FRunnableThreadWin::Run() [D:\TC_agent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Core\Private\Windows\WindowsRunnableThread.cpp:86]

![image](https://user-images.githubusercontent.com/118957669/203704313-5cc704b8-1713-453e-a9e3-aafaf777c366.png)

![image](https://user-images.githubusercontent.com/118957669/203704558-e29c8254-2974-45f6-8175-8116835f86d4.png)

![image](https://user-images.githubusercontent.com/118957669/203704657-b4c9d8d4-617c-414e-b51b-a8945de56610.png)

![image](https://user-images.githubusercontent.com/118957669/203704783-603007b2-46ee-4d43-b622-d73b1991e30d.png)

**Comment by mircearoata** [comment]
I can't believe it's crashing because I forgot some logging in...

**Comment by mircearoata** [comment]
Fixed in v0.3.8

**Comment by TheIntingFredi** [comment]
nice was fearing it would take quite some time till a fix realy cool to see it done so quick love this mod btw
