### ISSUE TITLE
Direction orientation wrong in the merger UI

### ISSUE THREAD

**Issue by Payne2000** [mircearoata/SatisfactoryAdvancedLogistics#3]
Hi,
first of all; I really love your mod. Great work.

I noticed, that the direction left/right in the merger UI menu is mirrored. 

I took some screenshots, to make it clear:

The splitter works fine and the direction is like the material flow, awsome:
![splitter_ok](https://user-images.githubusercontent.com/46223971/68090021-5c027280-fe6f-11e9-84f6-ea5a5c600acc.png)
![splitter_ui](https://user-images.githubusercontent.com/46223971/68090022-5c9b0900-fe6f-11e9-9a2a-6094959bd58f.png)

But the outputs of the MERGER is not in the flow direction, it is against it. That really confused me the first time. Here I just connected the middle an the right input, but the UI said that the middle and the left are connected.
![merger_wrong](https://user-images.githubusercontent.com/46223971/68090023-5c9b0900-fe6f-11e9-88df-afff126385d6.png)
![merger_ui](https://user-images.githubusercontent.com/46223971/68090024-5c9b0900-fe6f-11e9-9028-69bc32026e4a.png)

If you have questions please don't hesitate to contact me.
I hope you can fix this. Thanks a lot for this awsome mod, I use it a lot.

Happy building.

**Comment by jalil49** [comment]
Just posted a Pull request with a fix
