### ISSUE TITLE
Update 1.0

### ISSUE THREAD

**Issue by It1Proi** [mircearoata/SatisfactoryAdvancedLogistics#31]
Hello, Please can you update the mod for the 1.0 ?

**Comment by Frost212** [comment]
So this isn't specifically for you (Person who opened the issue) this is more for the mod author. I was able to get this mod working just by opening it up in unreal and letting alpakit recompile it. I haven't thoroughly tested it, but it appears to be splitting correctly, and it's not crashing (yet). The only minor issue i've noticed, is that the number text specifically in the box is barely readable (It's almost the same color as the box background) on sides that have a connected belt. If you could take a look at even just doing what i did to get the mod "useable" that'd be much appreciated @mircearoata

**Comment by mircearoata** [comment]
I have now released a new version for 1.0 support.

As for the number box, that was an old issue that came with U8, but apparently I had not pushed that version to github.
