### ISSUE TITLE
REQUEST

### ISSUE THREAD

**Issue by VincentBevort** [mircearoata/SatisfactoryAdvancedLogistics#4]
good work with thius splitter!.

But I am lokking for a splitter where I can set the number of items to send into a channel. Is this possible to make?

**Comment by mircearoata** [comment]
This is exactly what this splitter does

**Comment by VincentBevort** [comment]
I tried it but  I cannot set a value in the ratio fields

**Comment by VincentBevort** [comment]
maybe because I play EA

**Comment by mircearoata** [comment]
Mods only work on EA. Can you send a screenshot of what the menu looks like?

**Comment by VincentBevort** [comment]
merger: https://ibb.co/k42rcwL
Splitter: https://ibb.co/5M8w6PH

As you can see are the input fields greyed out and I cannot put anyting in it
Mod version Advanced Logistics-0.1.1
Satisfactory version 109075

**Comment by mircearoata** [comment]
You have to connect the belts thst you want to use first

**Comment by VincentBevort** [comment]
Would have been great if this kind of information was written in the ficsit.app or your GIT page.
This is not the way the default splitters behave. They can be configured stand alone WITHOUT any belts.

When publishing stuff make it clear for everybody HOW TO USE it.

**Comment by mircearoata** [comment]
This is not the way the default splitters behave because they dont have the UI for setting ratios.

**Comment by mircearoata** [comment]
And also,
![image](https://user-images.githubusercontent.com/19414258/71026365-c581cc00-2111-11ea-8eed-14f70e25a104.png)
and
![image](https://user-images.githubusercontent.com/19414258/71026375-cdda0700-2111-11ea-8425-14442922a128.png)
They both tell you why that number box is disabled
