### ISSUE TITLE
Placing on exiting belt does not auto attach to original belt

### ISSUE THREAD

**Issue by jalil29** [mircearoata/SatisfactoryAdvancedLogistics#5]
I attached the ratio splitter to a mk 4 belt in the latest version of the game and noticed two issues with it.
The first is that the belts do not self attach to the ratio splitter and would require recreating a belt to feed it and to be fed from.
The second issue is when the splitter is at an vertical angle the belt will attempt a sharp turn that would make dragging from an existing normal splitter unusable, but would work fine if worked backwards from the ratio splitter

**Comment by mircearoata** [comment]
I noticed that too, but I am yet to find out why that happens. I tried moving the inputs and outputs up and down, maybe it didn't recognize it, but it still didn't work

**Comment by jalil29** [comment]
My two-cents on the matter as someone with no experience in modding, is the external node rotating along with the spliter?
If the splitter is pitched 45 degree, is the external node also pitching 45 degrees? (not transitioning by 45 degrees).
I imagine that there are two nodes the internal and external, the internal one seems to be working properly, but the external one seems to be designed so that the belt will enter the splitter "correctly" so it doesn't clip through the body from a weird angle.

**Comment by mircearoata** [comment]
They should rotate like that because since they are inside the actor, their transform is relative to the parent.
