### ISSUE TITLE
[BUG] Lesser throughput

### ISSUE THREAD

**Issue by Netoen** [mircearoata/SatisfactoryAdvancedLogistics#6]
For some reason belt going into splitter stops every half a second or so.  
Two sides are filled, third is free, all three belts T1:  
![image](https://user-images.githubusercontent.com/6104611/76763348-fec6e800-67a3-11ea-8945-d5b285e5c77e.png)  
Tried with higher tiers of belts, no difference.  
If I empty other line a little bit - throughput is restored until the line buffers again.

**Comment by mircearoata** [comment]
Fixed it in 0.1.4. Thanks!
