### ISSUE TITLE
[MP] Game crashes for client

### ISSUE THREAD

**Issue by ReallyNotBad** [mircearoata/SatisfactoryAdvancedLogistics#7]
Hi,

I know that this mod is not meant to be for multiplayer. 
But is MP a feature u want to have for this mod in future?

Currently when the "if full" condition is met the client crashes!

Best Regards

**Comment by mircearoata** [comment]
I am working on MP compatibility, and I found that when a belt is connected to the splitter input it crashes. Does the if full crash happen only on the splitter or on both of them?

**Comment by ReallyNotBad** [comment]
Just tested the splitter for now. 
Yeah it crashes also on connecting the input of a splitter. But you can rejoin and then it is connected and works... as long as the if full condition is met.

If you need logs or so just tell me which ;)

**Comment by mircearoata** [comment]
Fixedᵀᴹ in the latest version
